### ISSUE TITLE
required validation not firing when required attribute applied on input

### ISSUE THREAD

**Issue by DuncanFaulkner** [rxweb/rxweb#392] opened 2020-08-26 13:22 UTC
# Describe the bug
With a required attribute on an input the rxwebvalidators.required() does not fire
after removing the required attribute the rxwebvalidation.required() does fire.

# Expected Behavior
should work whether required attribute is applied or not

# To Reproduce
<input
                #macAddress
                matInput
                placeholder="Mac Address"
                formControlName="macAddress"
                maxlength="17"
                required // remove this for it to work
              />

 RxwebValidators.required({message:'Mac Address is a required'})

# Url (stackblitz or plunker or other)

# Package Version
 "@rxweb/reactive-form-validators": "^2.0.0",

**Comment by ajayojha** [comment] 2020-08-27 10:47
@DuncanFaulkner The ```required``` validator is executing even though the ```required``` attribute is assigned on the element. The problem is the angular directive overrides the ```errors``` object key of ```required```. 

If you replace the ```rxRequired``` then you will get the same error object as ```required``` validator.

I think there is no further action required on this, hence I am closing this ticket. If you have any suggestion then feel free to reopen the ticket :).

**Closed by ajayojha** 2020-08-27 10:47 UTC

**Comment by DuncanFaulkner** [comment] 2020-08-28 14:18
ajayojha 
Thanks, only just discovered this library and finding my way around it.
Cheers
