### ISSUE TITLE
disable is not working

### ISSUE THREAD

**Issue by rodrigovillaca** [rxweb/rxweb#270] opened 2020-01-22 03:22 UTC
Hi I am really enjoying working with rxweb, I am having a issue with the disable decorator, no matter what I try it does not work.

This is the model class:
export class Class extends Base<Class> {
  @disable({
    conditionalExpression: (control: AbstractControl) => true
  })
  @prop({ isPrimaryKey: true })
  public id: number;

I am using matinput, I don't think is related as the control is not being disabled at all when I add a debugger after I create the formgroup, so I am doing this and it's fixing it for now, but I would like to inform that this functionality is not working.

 Thanks for your framework,

Rodrigo

**Comment by ajayojha** [comment] 2020-01-22 06:09
Thank You @rodrigovillaca. I will check and do the necessary changes to fix this issue. I will here as soon as it's done.

**Comment by ajayojha** [comment] 2020-01-29 14:19
Hi @rodrigovillaca , I have reproduced the issue in the stackblitz and it's not working. Sorry to say, but due to major code changes in the lib if I cover this case in the lib, so I would suggest It will be good if you apply logical condition in the conditional expression based upon the form control value/ object property value, that will work for sure. 

if you return without expression or fixed boolean value ```true``` or ```false```; like : ```conditionalExpression: (x) => x.toggle``` or ```conditionalExpression: (x) => true```  won't work in the conditional expression.

**Comment by ajayojha** [comment] 2020-01-31 14:09
@rodrigovillaca I am closing this ticket, as you can achieve the same with the alternative approach. Feel free to open a new ticket if you face any issue :)

**Closed by ajayojha** 2020-01-31 14:09 UTC

**Comment by mikaeldiener** [comment] 2021-03-05 17:00
**As @rodrigovillaca I'm really enjoying working with rxweb. However, I would like to reopen this issue. I´ve encountered the same problem. As of now, I have to write**

@disable({
    conditionalExpression: function () {
         return this.email === this.email;
    },
})
@prop()
email: string;

**to always disable a certain property. It would be really nice to be able to use this syntax for such cases:**

@disable()
@prop()
email: string;

**or at least:**

@disable({
    conditionalExpression: () => true
})
@prop()
email: string;
