### ISSUE TITLE
Client side model overwrite when we generate model.

### ISSUE THREAD

**Issue by devendraKLohar** [rxweb/rxweb#256] opened 2019-12-10 05:15 UTC
# Describe the bug
When we put decorator like @maxLength({value:100}),@prop({defaultValue:1}) in any property of model so it overwrite when we generate model

# Expected Behavior
When we put decorator like @maxLength({value:100}),@prop({defaultValue:1}) in any property of model so it should not be overwrite when we generate model.

# To Reproduce

# Url (stackblitz or plunker or other)

# Package Version
rxwebCore

**Comment by ajayojha** [comment] 2019-12-10 07:46
The issue is not related to the rxweb packages, Hence I am closing this ticket.

**Closed by ajayojha** 2019-12-10 07:46 UTC
