### ISSUE TITLE
Adding a mask to a mac validator

### ISSUE THREAD

**Issue by DuncanFaulkner** [rxweb/rxweb#391] opened 2020-08-26 12:56 UTC
# Describe the bug
when adding a mask to a mac address validator, returns invalid mac address, even though without the mask its valid. 
RxwebValidators.mask({ mask: '**:**:**:**:**:**'})

# Expected Behavior
validation to be correct

# To Reproduce
RxwebValidators.mac({message:'Invalid MAC address'}),
          RxwebValidators.mask({ mask: '**:**:**:**:**:**' }),
          RxwebValidators.maxLength({
            value: 17,
            message: 'Maximum 17 characters are allowed.',
          }),

# Url (stackblitz or plunker or other)

# Package Version
 "@rxweb/reactive-form-validators": "^2.0.0"

**Comment by ajayojha** [comment] 2020-08-27 11:49
@DuncanFaulkner Thanks for reporting this. I am considering this as a feature request. The provided code snippet is correct and working as expected. If we use a mac with mask validator then mask validator won't allow setting the value of ':' to the FormControl, that's the reason it's marking as invalid. 

I am thinking to provide an additional property(```valueWithMask```) in the ```MaskConfig``` which allows setting the value with the mask, like "94:37:0F:73:64:60".

**Comment by DuncanFaulkner** [comment] 2020-08-28 14:20
@ajayojha while you are doing this I guess the same applies to IP 4 addresses?

**Comment by ajayojha** [comment] 2020-08-28 14:38
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DuncanFaulkner** [comment] 2020-09-01 14:58
Do you have a time scale for when this feature will be added?

**Comment by ajayojha** [comment] 2020-09-01 15:00
I am planning to release this tomorrow.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DuncanFaulkner** [comment] 2020-09-01 15:02
excellent

**Comment by ajayojha** [comment] 2020-09-02 14:48
@DuncanFaulkner I have released the new version(2.1.0), please update the same. Please refer to the [example](https://stackblitz.com/edit/rxweb-mask-validator-for-mac-address?file=src%2Fapp%2Fmask-add.component.ts) to know how to part.

**Closed by ajayojha** 2020-09-02 14:48 UTC
Labels: Ready For Release, feature request

**Comment by DuncanFaulkner** [comment] 2020-09-02 15:09
will check this out, thanks

**Comment by DuncanFaulkner** [comment] 2020-09-02 15:22
Hi I updated to 2.1 - done a rebuild of project, (also done a remove of node_modules and a reinstall), this all seems to install OK.
When I try and run the application I get the following error:

ERROR in /home/duncan.faulkner/development/integra-frontend/node_modules/@rxweb/reactive-form-validators/__ivy_ngcc__/fesm2015/rxweb-reactive-form-validators.js
Module build failed (from /home/duncan.faulkner/development/integra-frontend/node_modules/@angular-devkit/build-angular/node_modules/babel-loader/lib/index.js):
TypeError: /home/duncan.faulkner/development/integra-frontend/node_modules/@rxweb/reactive-form-validators/__ivy_ngcc__/fesm2015/rxweb-reactive-form-validators.js: Column must be greater than or equal to 0, got -15
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/home/duncan.faulkner/development/integra-frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/core/node_modules/source-map/lib/source-map-consumer.js:543:13)
    at BasicSourceMapConsumer.SourceMapConsumer_allGeneratedPositionsFor [as allGeneratedPositionsFor] (/home/duncan.faulkner/development/integra-frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/core/node_modules/source-map/lib/source-map-consumer.js:201:22)
    at /home/duncan.faulkner/development/integra-frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/core/lib/transformation/file/merge-map.js:186:27
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/home/duncan.faulkner/development/integra-frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/core/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at buildMappingData (/home/duncan.faulkner/development/integra-frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/core/lib/transformation/file/merge-map.js:147:12)
    at mergeSourceMap (/home/duncan.faulkner/development/integra-frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/core/lib/transformation/file/merge-map.js:21:17)
    at generateCode (/home/duncan.faulkner/development/integra-frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/core/lib/transformation/file/generate.js:74:39)
    at run (/home/duncan.faulkner/development/integra-frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/core/lib/transformation/index.js:55:33)
    at run.next (<anonymous>)
    at Function.transform (/home/duncan.faulkner/development/integra-frontend/node_modules/@angular-devkit/build-angular/node_modules/@babel/core/lib/transform.js:27:41)
    at transform.next (<anonymous>)
    at step (/home/duncan.faulkner/development/integra-frontend/node_modules/gensync/index.js:254:32)
    at /home/duncan.faulkner/development/integra-frontend/node_modules/gensync/index.js:266:13
    at async.call.result.err.err (/home/duncan.faulkner/development/integra-frontend/node_modules/gensync/index.js:216:11)

**Comment by ajayojha** [comment] 2020-09-02 15:43
@DuncanFaulkner one which validation key you have set the validation message of "Column must be greater than or equal to 0, got -15"? 
it seems the library is throwing an error while loading a template.

**Comment by DuncanFaulkner** [comment] 2020-09-02 15:45
at the moment the project is only using required, ip and mac in one place in the application, I was waiting for the mask before I continued

**Comment by ajayojha** [comment] 2020-09-02 15:47
@DuncanFaulkner Ok Thanks, Please share the package.json so that I can try in my local environment.

**Comment by DuncanFaulkner** [comment] 2020-09-02 15:47
{
  "name": "integra-frontend",
  "version": "1.2.24",
  "license": "AST",
  "description": "INTEGRA Edge Administration Portal",
  "author": "Applied Satellite Technology Ltd",
  "contributors": [
    "Duncan Faulkner"
  ],
  "scripts": {
    "start": "ng serve integra-frontend",
    "lint": "nx workspace-lint && ng lint",
    "test": "./node_modules/.bin/jest --maxWorkers=2",
    "test:onlyChanged": "./node_modules/.bin/jest --onlyChanged",
    "test:watch": "./node_modules/.bin/jest --verbose --watchAll",
    "test:ci": "./node_modules/.bin/jest --runInBand",
    "test:coverage": "./node_modules/.bin/jest --coverage",
    "e2e": "ng e2e",
    "build-prod": "ng build --prod",
    "compodoc": "./node_modules/.bin/compodoc -d apps/integra-frontend/documentation -r 8090 -p apps/integra-frontend/tsconfig.json -s -w --theme vagrant --name 'Integra Edge'",
    "compodoc:ci": "./node_modules/.bin/compodoc -d apps/integra-frontend/documentation -p apps/integra-frontend/tsconfig.json --theme vagrant --name 'Integra Edge'",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "ng update @nrwl/workspace",
    "update:check": "ng update",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "nx": "nx",
    "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^10.0.12",
    "@angular/cdk": "^10.1.3",
    "@angular/common": "^10.0.12",
    "@angular/compiler": "^10.0.12",
    "@angular/core": "^10.0.12",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "^10.0.12",
    "@angular/material": "^10.1.3",
    "@angular/platform-browser": "^10.0.12",
    "@angular/platform-browser-dynamic": "^10.0.12",
    "@angular/router": "^10.0.12",
    "@angular/upgrade": "^10.0.12",
    "@auth0/angular-jwt": "^5.0.1",
    "@nrwl/angular": "^10.1.0",
    "@rxweb/reactive-form-validators": "^2.0.0",
    "@schematics/angular": "^10.0.7",
    "@swimlane/ngx-charts": "^14.0.0",
    "angular-svg-round-progressbar": "^3.0.1",
    "angular2-highcharts": "^0.5.5",
    "angular2-uuid": "^1.1.1",
    "core-js": "^3.6.5",
    "moment": "^2.27.0",
    "ng2-mqtt": "^0.1.2",
    "ngx-device-detector": "^1.4.6",
    "ngx-pipes": "^2.7.5",
    "rxjs": "^6.6.2",
    "ts-helpers": "^1.1.2",
    "tslib": "^2.0.1",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.7",
    "@angular/cli": "^10.0.7",
    "@angular/compiler-cli": "^10.0.12",
    "@angular/language-service": "^10.0.12",
    "@compodoc/compodoc": "^1.1.11",
    "@ngneat/spectator": "^5.13.0",
    "@nrwl/cypress": "^10.1.0",
    "@nrwl/jest": "^10.1.0",
    "@nrwl/workspace": "^10.1.0",
    "@types/jest": "^26.0.10",
    "@types/jsdom": "^16.2.3",
    "@types/lodash": "^4.14.160",
    "@types/node": "^14.6.0",
    "@types/uuid": "^8.3.0",
    "codelyzer": "^6.0.0",
    "cypress": "^5.0.0",
    "es6-promise-loader": "^1.0.2",
    "jest": "^26.4.2",
    "jest-preset-angular": "^8.3.1",
    "ng-mocks": "^10.1.2",
    "node-sass": "^4.14.1",
    "prettier": "^2.1.0",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.0.0",
    "tslint": "~6.1.3",
    "typescript": "^3.9.7"
  }
}

**Comment by ajayojha** [comment] 2020-09-02 16:15
@DuncanFaulkner it's working in my local environment with the latest package. I have committed the code on separate git repo(https://github.com/ajayojha/mask-example-error-project). I would suggest please clone it and run this project in your local environment. if still issue persists then please let me know the CLI version of the angular.

**Comment by DuncanFaulkner** [comment] 2020-09-02 21:21
angular cli 10.0.7 - from memory

**Comment by ajayojha** [comment] 2020-09-03 00:03
Did you get a chance to run the provided sample project in your environment?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DuncanFaulkner** [comment] 2020-09-03 08:14
Yes, sorry we probably have an 8 hour time difference, yes I did install your demo version and yes it did work.

I've gone back to my project and it doesn't. I have commented out all instances of RxWebValidators and RxReactiveFormsModule and the project builds fine as soon as I import the RxReactiveFormsModule it breaks (all validators at this point are still commented out).

**Comment by ajayojha** [comment] 2020-09-03 09:35
@DuncanFaulkner It's Ok, I googled about this issue and found one link(https://github.com/angular/protractor/issues/3103), please refer to this mentioned link, it may be helpful. I believe there is something related to the configuration, I will check from my end a little bit more to resolve this issue, will update you as soon as I have something.

**Comment by DuncanFaulkner** [comment] 2020-09-03 11:45
thanks

**Comment by DuncanFaulkner** [comment] 2020-09-03 12:44
I've just turned off source map for dev builds and it now compiles, though I'm now having another issue with the old charting software. I did see similar errors when I was doing a google search and source maps where mentioned not sure what the issue is with source maps and why it's now complaining.

For the moment I will revert back to version 2 - hopefully you will be able to track the issue and fix it.

I will keep you posted should I discover anything else

**Comment by DuncanFaulkner** [comment] 2020-09-03 16:00
Was doing further testing and another component started to fail (which was odd as it hadn't before), I eventually rolled my branch back as I couldn't work out why the highcharts was now failing (they need replacing, but that's planned for later on). 

With Ivy switched on everything seemed to be working until I updated to 2.1.0 of RxWeb, I've now turned Ivy Off and version 2.1.0 of RxWebValidators now works, so I'm of the thinking that highcharts (and a couple of other libraries) with Ivy on and on version 10.1.0 of Angular doesn't work.

Will now check to see if migrating to ng 10 (with Ivy off) works as well.

Was hoping not to turn Ivy Off, but I guess until I can replace these older libraries I'm stuck with Ivy Off.

Now to work on adding the masks in - Thanks for all your help.

**Comment by ajayojha** [comment] 2020-09-03 16:12
I really appreciate your quick update on this with the detailed information.
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DuncanFaulkner** [comment] 2020-09-04 09:59
Just to let you know this is all now working (in Angular 9 at least) will update when I migrate to Angular 10.

I have noticed that your component for MAC address is logging values to the console, not a big issue just thought I would mention it.

**Comment by ajayojha** [comment] 2020-09-04 10:04
@DuncanFaulkner Thanks for the update. A silly mistake from my end, I will fix the same in the upcoming release.

**Comment by DuncanFaulkner** [comment] 2020-09-04 10:27
How does the mask work for IP addresses? 
I've set the mask to be 999.999.999.999
but each octet can be 1 to 3 numbers if I have an ip address of 10.20.30.40 I now need to enter 010.020.030.040 which feels a little odd, is there away to allow the mask to accept either 1, 2 and 3 digits in each octet.

**Comment by ajayojha** [comment] 2020-09-04 10:32
@DuncanFaulkner Sorry, but as such, there is no feature available that allows the optional value in each octet.

**Comment by DuncanFaulkner** [comment] 2020-09-04 10:40
OK

**Comment by DuncanFaulkner** [comment] 2020-09-04 10:54
ok

**Comment by DuncanFaulkner** [comment] 2020-09-14 20:21
Hi any luck with the IP address mask?

**Comment by silveoj** [comment] 2020-10-09 14:45
`@rxweb/reactive-form-validators": "2.1.2"`

I get the same error with rxweb and ivy after migration from Angular 8 to 10.
`build` and `serve` work but tests for jasmine doesn't work.

```
ERROR in ./node_modules/@rxweb/reactive-form-validators/__ivy_ngcc__/fesm2015/rxweb-reactive-form-validators.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: C:\myProject\node_modules\@rxweb\reactive-form-validators\__ivy_ngcc__\fesm2015\rxweb-reactive-form-validators.js: Column must be greater than or equal to 0, got -15
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (C:\myProject\node_modules\@babel\core\node_modules\source-map\lib\source-map-consumer.js:543:13)
    at BasicSourceMapConsumer.SourceMapConsumer_allGeneratedPositionsFor [as allGeneratedPositionsFor] (C:\myProject\node_modules\@babel\core\node_modules\source-map\lib\source-map-consumer.js:201:22)
    at C:\myProject\node_modules\@babel\core\lib\transformation\file\merge-map.js:186:27
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (C:\myProject\node_modules\@babel\core\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at buildMappingData (C:\myProject\node_modules\@babel\core\lib\transformation\file\merge-map.js:147:12)
    at mergeSourceMap (C:\myProject\node_modules\@babel\core\lib\transformation\file\merge-map.js:21:17)
    at generateCode (C:\myProject\node_modules\@babel\core\lib\transformation\file\generate.js:74:39)
    at run (C:\myProject\node_modules\@babel\core\lib\transformation\index.js:55:33)
    at run.next (<anonymous>)
    at Function.transform (C:\myProject\node_modules\@babel\core\lib\transform.js:27:41)
    at transform.next (<anonymous>)
    at step (C:\myProject\node_modules\gensync\index.js:254:32)
    at C:\myProject\node_modules\gensync\index.js:266:13
    at async.call.result.err.err (C:\myProject\node_modules\gensync\index.js:216:11)
    at C:\myProject\node_modules\gensync\index.js:184:28
```

With v 2.0.0 or 2.1.0 I get
`'dirty' is defined as an accessor in class 'FormControl', but is overridden here in 'RxFormControl' as an instance property.`

**Comment by silveoj** [comment] 2020-10-09 14:47
`@rxweb/reactive-form-validators": "2.1.2"`

I get the same error with rxweb and ivy after migration from Angular 8 to 10:
`Column must be greater than or equal to 0, got -15`
`build` and `serve` work but tests for jasmine doesn't work.

```
ERROR in ./node_modules/@rxweb/reactive-form-validators/__ivy_ngcc__/fesm2015/rxweb-reactive-form-validators.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: C:\myProject\node_modules\@rxweb\reactive-form-validators\__ivy_ngcc__\fesm2015\rxweb-reactive-form-validators.js: Column must be greater than or equal to 0, got -15
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (C:\myProject\node_modules\@babel\core\node_modules\source-map\lib\source-map-consumer.js:543:13)
    at BasicSourceMapConsumer.SourceMapConsumer_allGeneratedPositionsFor [as allGeneratedPositionsFor] (C:\myProject\node_modules\@babel\core\node_modules\source-map\lib\source-map-consumer.js:201:22)
    at C:\myProject\node_modules\@babel\core\lib\transformation\file\merge-map.js:186:27
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (C:\myProject\node_modules\@babel\core\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at buildMappingData (C:\myProject\node_modules\@babel\core\lib\transformation\file\merge-map.js:147:12)
    at mergeSourceMap (C:\myProject\node_modules\@babel\core\lib\transformation\file\merge-map.js:21:17)
    at generateCode (C:\myProject\node_modules\@babel\core\lib\transformation\file\generate.js:74:39)
    at run (C:\myProject\node_modules\@babel\core\lib\transformation\index.js:55:33)
    at run.next (<anonymous>)
    at Function.transform (C:\myProject\node_modules\@babel\core\lib\transform.js:27:41)
    at transform.next (<anonymous>)
    at step (C:\myProject\node_modules\gensync\index.js:254:32)
    at C:\myProject\node_modules\gensync\index.js:266:13
    at async.call.result.err.err (C:\myProject\node_modules\gensync\index.js:216:11)
    at C:\myProject\node_modules\gensync\index.js:184:28
```

With v 2.0.0 or 2.1.0 I get
`'dirty' is defined as an accessor in class 'FormControl', but is overridden here in 'RxFormControl' as an instance property.`

**Comment by ajayojha** [comment] 2020-10-13 12:19
@silveoj 'dirty' issue is resolved in 2.1.2 release.  regarding this ```Column must be greater than or equal to 0, got -15``` I have to find out the cause of this issue. will fix as soon as I have something.

**Comment by ajayojha** [comment] 2020-10-13 12:20
> Hi any luck with the IP address mask?

@DuncanFaulkner Sorry, I forgot to add this, will try to add this in upcoming release.

**Comment by DuncanFaulkner** [comment] 2020-10-13 21:43
Thanks - that would be great thanks

**Comment by DuncanFaulkner** [comment] 2020-11-02 11:49
Any update on the IP address mask, being able to enter 192.168.1.254 instead of 192.168.001.254

**Comment by silveoj** [comment] 2021-01-16 01:01
`"@rxweb/reactive-form-validators": "2.1.2"`

To avoid `Column must be greater than or equal to 0, got -15` in karma testing I added
`tsconfig.spec.json`
```
  "angularCompilerOptions": {
    "enableIvy": false
  },
```

tsconfig.spec.json
