### ISSUE TITLE
Multiple Popup close issue

### ISSUE THREAD

**Issue by kalathiyan** [rxweb/rxweb#397] opened 2020-09-04 04:39 UTC
# Describe the bug

When we open popup over popup then only top most popup getting closed
other popup close is not working and getting error in console

# Expected Behavior

Multiple popup should be closed

# To Reproduce

attached stackblitz Url and steps also mentioned there

# Url (stackblitz or plunker or other)

https://stackblitz.com/edit/angular-rx-multi-popup-close-issue-3nwcag

# Package Version

"@rxweb/angular": "0.0.2-beta4",
    "@rxweb/angular-localization": "0.0.1",
    "@rxweb/angular-router": "0.0.2-beta4",
    "@rxweb/core": "0.0.1-beta1",
    "@rxweb/dom": "0.0.2-beta2",
    "@rxweb/framework": "0.0.1",
    "@rxweb/generics": "0.0.1-4",
    "@rxweb/grid": "0.0.2-beta5",
    "@rxweb/http": "0.0.1",
    "@rxweb/js": "0.0.1-beta1",
    "@rxweb/localization": "0.0.2-beta2",
    "@rxweb/reactive-form-validators": "^1.9.9-beta1",
    "@rxweb/storage": "0.0.2-beta2",

**Comment by ajayojha** [comment] 2020-09-14 12:25
@kalathiyan the issue is already fixed in "0.0.1" version of "@rxweb/js", please update the same.

after updating the package you have to change the minor code in the 'modal.ts' file. here is the code:

```js
resolver = (component: ComponentType<any>, params?: {
        [key: string]: any;
    }): {element:HTMLElement,destroy:Function} => {
        let componentFactory = this.componentFactoryResolver.resolveComponentFactory(component);
        this.componentRef = this.viewContainerRef.createComponent(componentFactory, this.viewContainerRef.length, this.viewContainerRef.parentInjector);
        if (params)
            this.setParams(params);
            // init method called by component and from here as well so commented
        // this.componentRef.instance["ngOnInit"]();
        return { element:this.rootNode(),destroy:this.destroy(this.componentRef)}
    }
    destroy(componentRef)  {
        return ()=>{
            if (componentRef) {
                componentRef.destroy();
                componentRef = undefined;
            }
        }
    }
```
Replace the above code with the existing code.

Please refer to the stackblitz [updated code example](https://stackblitz.com/edit/angular-rx-multi-popup-close-issue-6otpkr?file=src%2Fapp%2Fmodal%2Fmodal.ts).

**Closed by ajayojha** 2020-09-14 12:25 UTC
