### ISSUE TITLE
RxWebValidators.pattern does not work

### ISSUE THREAD

**Issue by bruceauyeung** [rxweb/rxweb#69] opened 2019-01-02 09:48 UTC
# Describe the bug

https://stackblitz.com/angular/rdapbxjraln?file=src%2Fapp%2Fpattern-add.component.ts

even if you type in only letters, it still validate to false.
i can reproduce this bug in my local env.

# Expected Behavior

# To Reproduce

# Url (stackblitz or plunker or other)

# Package Version
@rxweb/<package-name>@<packageversion>

**Comment by ajayojha** [comment] 2019-01-02 11:19
Thanks for reporting this issue.

I would suggest try to use pattern without calling **RegExp** constructor. I have replaced the code as below :
**Current Code :** 
```js
RxwebValidators.pattern({expression:{'onlyAlpha': RegExp('/^[A-Za-z]+$/')} })
```

**Replace Code:**
```js
RxwebValidators.pattern({expression:{'onlyAlpha': /^[A-Za-z]+$/} })
```
The same thing I have updated in [stackblitz ](https://stackblitz.com/edit/angular-rxweb-pattern-validator?file=src/app/pattern-add.component.ts) example.

I am considering this as a example bug, because our example is also not working.

Please let me know, if it's not working in your local project.

**Comment by bruceauyeung** [comment] 2019-01-03 01:06
your newly provided example codes works well in my local env, thanks for your great work! @ajayojha

**Comment by AndersonSFerreira** [comment] 2019-08-01 12:03
When using the sample code as mentioned:
`RxwebValidators.pattern ({expression: {'onlyAlpha': RegExp ('/ ^ [A-Za-z] + $ /')}})`

validation using patterns doesn't work, the problem is that i'm using it through decorators and how the components related to this validation are inside a library when i try to use the recommended form like:
`RxwebValidators.pattern ({expression: {'onlyAlpha': / ^ [A-Za-z] + $ /}})`

errors occur when compiling components for the library using ng-packagr

Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic": "error", "message": "Expression not supported", "line": 27, "character": 19}

in the model class:
`@pattern({
        expression: {
            'url': /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/
        },
        message: 'Invalid URL.'
    })
    @maxLength({ value: 100 })
    Url: string;`

**Comment by ajayojha** [comment] 2019-08-01 13:35
@AndersonSFerreira Sorry, I didn't understand completly your comment. Let me frame what I understood, I believe you are talking about the issue (**```Expression not supported```**) while compiling through the `ng-packagr`.

Please correct me if I am wrong, your second concern is to bind the validation pattern through component instead of applying through the decorator. Please share your inputs.

Regarding the first concern, I will update you soon.

**Comment by ajayojha** [comment] 2019-08-11 16:10
@AndersonSFerreira I have tested both regexes in my machine and it works perfectly without string quoted. Would be great if you share a little bit more info. 

Whenever you plan to provide the more information, would be good if you create a separate ticket for that :)

Hence I am closing this ticket, for now, will wait for your detailed information.

**Closed by ajayojha** 2019-08-11 16:10 UTC
Labels: bug, example, pattern
