### ISSUE TITLE
updateValueAndValidity for RxFormGroup and RxFormArray not working for children controls

### ISSUE THREAD

**Issue by Xambey** [rxweb/rxweb#513] opened 2021-08-12 10:16 UTC
# Describe the bug

updateValueAndValidity for RxFormGroup and RxFormArray not working for children controls

# Expected Behavior

children's controls also double-check their validity

# To Reproduce

I have an rxFormGroup created via rxFormBuilder.formGroup(my model):
```typescript
export class PurchaseOffer implements IPurchaseOffer {
    @prop()
    id: number;
    @prop()
    contractorId: number;
    @prop()
    contractorName: string;
    @prop()
    amount: number;
    @prop()
    currency: string;
    @prop()
    offerDate: Date;
    @prop()
    description: string;
    @prop()
    status: OfferStatus;
    @prop()
    rejectReason: string;
    @prop()
    fromEtp: boolean;
    @prop()
    etp: TradingPlatform;
    @prop()
    externalId: string;
    @prop()
    offerDocuments: IOfferDocument[];
    @required({conditionalExpression: (model: PurchaseOffer) => {
            console.log('required', model.selected)

            return model.selected;
        }})
    @prop()
    withVat: boolean | null = null;

    @prop()
    selected = false;

    constructor(data: IPurchaseOffer) {
        this.id = data?.id;
        this.contractorId = data?.contractorId;
        this.contractorName = data?.contractorName;
        this.amount = data?.amount;
        this.currency = data?.currency;
        this.offerDate = data?.offerDate;
        this.description = data?.description;
        this.status = data?.status;
        this.rejectReason = data?.rejectReason;
        this.fromEtp = data?.fromEtp;
        this.etp = data?.etp;
        this.externalId = data?.externalId;
        this.offerDocuments = data?.offerDocuments;
        this.withVat = data?.withVat;
    }
}
```

When i call updateValueAndValidity() for the withVat control, then conditionalExpression recheched but, if i do it for formGroup with the options: {onlySelf: false, emitEvent: true}, i**t's not called** 

# Url (stackblitz or plunker or other)
----------

# Package Version
@rxweb/reactive-form-validators": "2.1.2

**Comment by ajayojha** [comment] 2021-09-07 10:39
@Xambey FormGroup Object is also not calling the children's controls, please refer to this [example](https://stackblitz.com/edit/angular-ivy-ur42gr?file=src%2Fapp%2Fapp.component.ts).

I am closing this ticket. you can reopen the same if the problem is different.

**Closed by ajayojha** 2021-09-07 10:39 UTC
