### ISSUE TITLE
Checked Property is not working in dynamicReactiveForm

### ISSUE THREAD

**Issue by KamleshDedasaniya** [rxweb/rxweb#211] opened 2019-09-19 06:31 UTC
Hi,

"https://stackblitz.com/angular/keyjomvlkvg?file=src%2Fapp%2Fcheckbox-selectall.component.ts"

In this link 

For the checkbox in source checked property is not working properly

**Comment by ajayojha** [comment] 2019-10-06 09:16
Thanks @KamleshDedasaniya for providing the stackblitz link. The issue is with the mentioned condition  ``` if (!this.controlsConfig.hobbies.value) {```in the ```source.ts``` file. Please check the length and all instead of checking the null value.

I am closing this ticket. Feel free to open a new ticket if you have any concerns.

**Closed by ajayojha** 2019-10-06 09:16 UTC
