### ISSUE TITLE
Angular 13 - reactive-form-validators ivy enabled

### ISSUE THREAD

**Issue by mikerentmeister** [rxweb/rxweb#542] opened 2021-11-12 18:48 UTC
### Description
Now that Angular 13 is released and view engine is deprecated, does this team have any plans on updating reactive-form-validators to be built in at least partial ivy mode, in order to not need to run ngcc for this library? Currently ngcc is the only thing in the way of my team being able to update to yarn 2 with PnP.

### Describe the solution you'd like
reactive-form-validators library built with "compilationMode": "partial" and "enableIvy": true

**Comment by tim-blome** [comment] 2022-04-08 12:20
Hi, looks like this also causes Jest UnitTests with ng13 to fail. After updating to Angular13 our UnitTests for Components that used the RXFormBuilder suddenly failed in a similar way as described here: [https://github.com/ngneat/reactive-forms/issues/118](https://github.com/ngneat/reactive-forms/issues/118), caused by incompatibility with Angular13.

**Comment by ajayojha** [comment] 2022-04-13 14:31
@tim-blome would be great if you share the issue repo. I tried but didn't get any error, maybe I am missing something.

**Comment by KiranMantha** [comment] 2022-04-21 05:58
@ajayojha I'm too facing the same issue with angular@13.3.4. the application itself is not getting compiled and failing with below error:

```
Error in turbo_modules/@rxweb/reactive-form-validators@2.1.6/services/reactive-form.module.d.ts (2:22)
Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the dependency (@rxweb/reactive-form-validators) which declares RxReactiveFormsModule has not been processed correctly by ngcc.
```

Here is the stackblitz [link](https://stackblitz.com/edit/angular-ivy-rrpntj?file=src/app/app.module.ts) for reference

**Comment by ajayojha** [comment] 2022-04-21 06:12
@KiranMantha I have downloaded the stackblitz code and tried to run the same in my local but it's not working, as this is showing a different error than the mentioned issue you have highlighted. I am keen to solve this issue, but for this, I would need an issue repo. Would be great if you share the issue repo with minimal code [nonproduction code].

**Comment by tamyfabius** [comment] 2022-04-21 14:47
I have created a new NX Angular 13 project with the latest Jest version and The test fails when creating a RxFormGroup. I seen a discussion about this error, I don't know there are a fix about this:

==> TypeError: Class constructor FormControl cannot be invoked without 'new'

**Comment by ajayojha** [comment] 2022-05-09 13:14
Please check with 2.1.7 version, I will close this ticket once I get an update from anyone of you.

**Comment by mikerentmeister** [comment] 2022-05-09 14:25
2.1.7 shows that this package is still not ivy compatible: 
![image](https://user-images.githubusercontent.com/18708788/167431431-792ffd7c-1331-4312-b965-d18afd5ccd66.png)

**Comment by tamyfabius** [comment] 2022-05-12 10:17
@ajayojha,
After check, I still have the same error **Class constructor FormControl cannot be invoked without 'new'** with  2.1.7 version.

And this package is still not ivy compatible

**Comment by sozzzzz** [comment] 2022-05-26 19:38
Same issue `TypeError: Class constructor FormControl cannot be invoked without 'new'`

"@rxweb/reactive-form-validators": "^2.1.7",
"jest": "^28.1.0",

**Comment by SmailHammour** [comment] 2022-06-13 10:43
> Please check with 2.1.7 version, I will close this ticket once I get an update from anyone of you.

I can conform that 2.1.7 still throws this warning.

**Comment by sahofmann** [comment] 2022-06-28 13:29
We also had no luck updating to 2.1.7 and blocks our Angular 13 - Upgrade.

@ajayojha 
During the overall upgrade - process we also had issues with libraries not being ivy compatible. We've fixed be upgrading targets and libs in our tsconfigs. I see that you're also still using `es5` as a target.
So we've used the following language versions:
```json
"target": "es2017",
"module": "es2020",
 "lib": ["es2020", "dom"]
```

We've also removed `angularCompilerOptions` completely and let angular doing its thing.

Don't know if it helps in this case but I guess upgrading the `target` could do the trick.

**Comment by sahofmann** [comment] 2022-06-29 14:10
Nevermind. With the decision to create a PR I've played around with the settings.
First of all I've bumped the language version but still got the "Processing legacy View Engine" messages and errors during test. Then I've added `"enableIvy: true"` in the tsconfig.lib.prod.json (which was missing anyway) but this even changed anything.
After all I didn't got it to output an ivy compilation at all. May I've missed something.

Anyway, it would be great to have a better contribution guide with steps how to build locally. I've ended up performing  a `npm install` in `client-side/angular`, `ng build @rxweb/reactive-form-validators` and `npm publish --registry http://localhost:4873` from within the dist, using verdaccio.

**Comment by sahofmann** [comment] 2022-06-30 07:15
@ajayojha 

Still getting `TypeError: Class constructor FormControl cannot be invoked without 'new'` but Ivy compilation works. I'm not quite sure if it makes any sense to provide a PR fixing the ivy compilation while not fixing this "new" bug. Even switching to ivy would break compatibility with non-ivy-projects.
So for now I'm not quite sure what is causing the issue. That's what I've done so far:
https://github.com/sahofmann/rxweb/commit/0dfd251aac0b7322827a53171f775f0e94c3fcf6

Didn't found a way to add ` --configuration production` to CI as it's not clear how you've set it up. Found `yarn prod`, but not sure what it does in your setup. But if the library was ever built in production mode your builds would've crashed due to missing `ng-package.prod.json`.

**Comment by sahofmann** [comment] 2022-06-30 10:15
So ... after all 2 PRs:

The first one fixes Ivy compilation but still throws `Class constructor FormControl …` and needs adjustments on how you built your libraries.

The second one bumps the whole client-side project to Angular 13 with all it's shiny advantages. With this PR all errors are gone and compiles perfectly. But you still have to check if it works for your RxWeb environment.

It's your's to choose ;) (or abandon both)

**Comment by ajayojha** [comment] 2022-06-30 10:20
Thank You So Much @sahofmann, I really appreciate your efforts in fixing the issue, Soon, I will review and merge the same :).

**Comment by ajayojha** [comment] 2022-07-03 12:32
@sahofmann if you have a sample code of producing this issue "**throws Class constructor FormControl**", then please share the same.

**Comment by sahofmann** [comment] 2022-07-03 13:55
This error has gone with to the Angular 13 update you've already merged. Thanks for that. If you still need a sample let me know.

**Comment by matusko89** [comment] 2022-07-27 13:40
Hey, will there be a new release with this fix?

**Comment by nita-au** [comment] 2022-08-13 03:41
Any update on an upcoming version for this fix?

**Comment by ajayojha** [comment] 2022-08-24 13:31
if anyone tests this build copy in their machine, if it's working then I release the same. I appreciate @sahofmann work on this issue but I was facing some issues with my machine for creating a build copy. I would request if anyone spare some time to test with this [build copy](https://tez.blob.core.windows.net/tez/reactive-form-validators.rar).

**Comment by mikerentmeister** [comment] 2022-10-20 03:25
Any update on this by chance?

**Comment by ajayojha** [comment] 2022-10-20 11:46
@mikerentmeister I have attached a build copy of the package in my previous comment, would be great if you/someone else check in the local environment, if everything works well then would be happy to release the same :).

**Comment by jgomesmv** [comment] 2022-11-21 15:17
@ajayojha I tried to run the command `ng build reactive-form-validators` but it didn't work.
I believe it's due to the fact that angular.json is missing:
![image](https://user-images.githubusercontent.com/8100887/203090506-6e77b4ae-13f2-41f0-96b2-2e7de9be2a73.png)

Do you mind to publish a release candidate version on NPM so that we can easily install and test? 

Thanks for the help!

**Comment by ajayojha** [comment] 2022-11-23 05:44
@jgomesmv I have released the [rc version](https://www.npmjs.com/package/@rxweb/reactive-form-validators/v/13.0.0-rc.0), please check the same.

**Comment by jgomesmv** [comment] 2022-11-23 09:45
@ajayojha I have tested [rc version](https://www.npmjs.com/package/@rxweb/reactive-form-validators/v/13.0.0-rc.0):
- Install no longer showns any error
- I have used a few validators like: greaterThen, lessThen, noneOf

Good job! Everything works as expected! Thanks a lot for the help!

I have checked this branches package.json:
[Master](https://github.com/rxweb/rxweb/blob/master/client-side/angular/package.json)
[Development](https://github.com/rxweb/rxweb/blob/Development/client-side/angular/package.json)
[revert-585-upgrade-to-angular-13](https://github.com/rxweb/rxweb/blob/revert-585-upgrade-to-angular-13/client-side/angular/package.json)

In all of them you are using angular 12. Are there any plans to support angular 13, 14 and 15?

Cheers!

**Comment by ajayojha** [comment] 2022-11-23 09:54
@jgomesmv Thanks for the update. I am going to create a separate branch for angular 13 & above support and the release version starts with 1X.X.X....

**Comment by ajayojha** [comment] 2022-11-23 11:30
I am closing this ticket as the issue has been resolved and the [stable version ](https://www.npmjs.com/package/@rxweb/reactive-form-validators/v/13.0.0) (13.0.0) has been released. 

Thanks to everyone who has helped with this issue :).

**Closed by ajayojha** 2022-11-23 11:30 UTC
Labels: Ready For Release, @rxweb/reactive-form-validators

**Comment by sahofmann** [comment] 2022-11-30 10:24
Hi, first of all, sorry that my PR caused more issues than it solved.
We've faced that Version 13 ist only compatible with at least Angular 14 and produces errors in Angular 13 - Projects. I need to do some tests on this but for now we stick to the "dirty" fixed version I provided as a PR.
